### ISSUE TITLE
Null Pointer Exception in Entity_SpecialZombie during attackOnCollide

### ISSUE THREAD

**Issue by UndeadZeratul** [FatherToast/SpecialMobs#1] opened 2016-03-30 18:08 UTC
From [here](https://github.com/UndeadZeratul/ThereWillBeBlood/issues/129)

I have Special Mobs v3.2.1, but it doesn't look like 3.2.2 changed the method that I see in the stack trace that points to your mod; feel free to correct me if I'm mistaken.

It looks like [this](https://github.com/FatherToast/SpecialMobs/blob/master/src/main/java/toast/specialMobs/entity/zombie/Entity_SpecialZombie.java#L153-L156) is the method that was broken, although I'm not sure what exactly is causing it to fail because aside from this line, the rest of the stacktrace is in vanilla's code.

Any thoughts?

**Comment by FatherToast** [comment] 2016-07-27 04:25
I believe this is an error caused by AI swapping during an attack via [this](https://github.com/FatherToast/SpecialMobs/blob/master/src/main/java/toast/specialMobs/entity/zombie/Entity_SpecialZombie.java#L220-L225) method.
This will be fixed in a later version for both zombies and skeletons.

**Closed** 2019-04-01 15:06 UTC
